### ISSUE TITLE
Create Account bug - valid password

### ISSUE THREAD

**Issue by SarahL88** [hicsail/noise-score#2]
Check if these errors are still occurring.  They might be fixed now.

1) I've tried a few different passwords, but can't get past the 'Please enter a valid password' error.  

![Screen Shot 2019-06-23 at 10 34 16 AM](https://user-images.githubusercontent.com/14101377/59977695-947d7000-95a2-11e9-849c-677f632f5b24.png)

2) The Login page gets stuck with a 'Strong Password' error.  I can't erase the previous password to try a new password.

![Screen Shot 2019-06-23 at 10 37 11 AM](https://user-images.githubusercontent.com/14101377/59977727-fd64e800-95a2-11e9-93e6-9f316e25437f.png)

**Comment by stathisKara** [comment]
Created new password validator that works as needed.
